org: wilkcaetano
app: gamehash
service: gamehash

frameworkVersion: "2"

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: "20201221"

package:
  exclude:
    - __tests__/**
    - jest*
    - .eslintrc.js
    - test-api/**
    - yarn.lock
    - package-lock.json
    - node_modules/aws-sdk/**
    - coverage/**
    - .vscode/**
    - .env
    - .env.test

functions:
  board:
    handler: src/handler/handlerHash.handler
    events:
      - http:
          path: /
          method: get
          cors: true
  