org: wilkcaetano
app: gamehash
service: gamehash

frameworkVersion: "2"

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: "20201221"

functions:
  board:
    handler: src/handler/handlerHash.handler
    events:
      - http:
          path: /
          method: get
          cors: true
          request:
            parameters:
              querystrings:
                url: true
